spring:
  application:
    name: produtosapi
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2-console 